### ISSUE TITLE
Evaluate on reverse language pairs

### ISSUE THREAD

**Issue by xu3kev** [eaplatanios/symphony-mt#3]
It says in the option "--only-forward" that the model will be trained and evaluated only on forward translation for the provided language pairs. However, when I run the training without this option, it only shows the forward translation for the provided language pairs.
What should I do to show the evaluation results on both forward and backward translation of the provided language pairs like in the paper?

**Comment by xu3kev** [comment]
Leaving the evaluation languages variable empty in the config files will make it evaluate on all training language pair.

**Comment by eaplatanios** [comment]
@xu3kev I'm glad you figured this out. Sorry I didn't see this earlier but I was very busy with the ICML deadline.

**Comment by xu3kev** [comment]
Really appreciate your reply and this awesome machine translation library!
However, after digging into the source code, I still have trouble reproducing the results. Let me open another issue for the problem.
